postgresql:
    image: postgres:12
    container_name: jpa-postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: jpa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jpa
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"